routes/web.php
<?php
use App\DataTables\PruebaDataTable;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
// Route::get('/creditosVencidos', 'CreditosController@creditosVencidos')->name('credito.creditosVencidos');
//Rutas para gastos
Route::get('gastos/index', ['as' => 'gastos.index', 'uses' => 'ExtraController@indexGastos'])->middleware('auth');
Route::post('gastos/store', ['as' => 'gastos.store', 'uses' => 'ExtraController@storeGastos'])->middleware('auth');
Route::get('gastos/api', ['as' => 'gastos.api', 'uses' => 'ExtraController@apiGasto'])->middleware('auth');
Route::get('gastos/edit/{id}', ['as' => 'gastos.edit', 'uses' => 'ExtraController@gastosEdit'])->middleware('auth');
Route::post('gastos/update' ,['as' => 'gastos.update', 'uses' => 'ExtraController@gastosUpdate'])->middleware('auth');
Route::get('eliminargasto/', ['as' => 'gastos.eliminargasto', 'uses' => 'ExtraController@eliminargasto'])->middleware('auth');
Route::get('gastos/foto/{id}', ['as' => 'gastos.foto', 'uses' => 'ExtraController@gastosFoto'])->middleware('auth');

//Capital secundario
Route::get('capital/secundario/index', ['as' => 'capital.secundario.index', 'uses' => 'ExtraController@indexCapital'])->middleware('auth');
Route::get('capital/secundario/api', ['as' => 'capital.secundario.api', 'uses' => 'ExtraController@apiCapital'])->middleware('auth');

//Ingresos extras
Route::get('ingreso/index', ['as' => 'ingreso.index', 'uses' => 'ExtraController@indexIngreso'])->middleware('auth');
Route::post('ingreso/store', ['as' => 'ingreso.store', 'uses' => 'ExtraController@storeIngreso'])->middleware('auth');
Route::match(['GET', 'POST'], 'tipo_ingreso/modal/create', 'ExtraController@tipo_gasto_modal')->name('tipo_ingreso.modal.create')->middleware('auth');
Route::get('/tabla/ingreso', 'ExtraController@tablaIngreso')->name('tabla.ingreso');
Route::get('ingreso/api', ['as' => 'ingresos.api', 'uses' => 'ExtraController@apiIngreso'])->middleware('auth');
Route::get('/tabla/tipo/ingreso', 'ExtraController@tablaTipo')->name('tabla.tipo.ingreso');
Route::get('tipo/ingreso/api', ['as' => 'tipo.ingresos.api', 'uses' => 'ExtraController@apiTipoIngreso'])->middleware('auth');
Route::get('ingreso/edit/{id}', ['as' => 'ingreso.edit', 'uses' => 'ExtraController@ingresoEdit'])->middleware('auth');
Route::post('ingreso/update' ,['as' => 'ingreso.update', 'uses' => 'ExtraController@ingresoUpdate'])->middleware('auth');
Route::get('eliminaringreso/', ['as' => 'ingreso.eliminaringreso', 'uses' => 'ExtraController@eliminarIngreso'])->middleware('auth');
Route::get('ingreso/foto/{id}', ['as' => 'ingreso.foto', 'uses' => 'ExtraController@ingresoFoto'])->middleware('auth');
Route::get('tipo/ingreso/edit/{id}', ['as' => 'tipo.ingreso.edit', 'uses' => 'ExtraController@tipoIngresoEdit'])->middleware('auth');
Route::post('tipo/ingreso/update' ,['as' => 'tipo.ingreso.update', 'uses' => 'ExtraController@tipoIngresoUpdate'])->middleware('auth');
Route::get('eliminartipoingreso/', ['as' => 'tipo.ingreso.eliminar', 'uses' => 'ExtraController@eliminarTipoIngreso'])->middleware('auth');

Route::get('fichasDiarias' , 'PagoController@fichasDiarias');
Route::get('fichasSemanales' , 'PagoController@fichasSemanales');
Route::get('fichasQuincena' , 'PagoController@fichasQuincena');
Route::get('primerPasoSemanal/' , 'PagoController@primerPasoSemanal');
Route::get('primerPasoDiario/' , 'PagoController@primerPasoDiario');
Route::get('primerPasoQuincena/' , 'PagoController@primerPasoQuincena');

Route::get('elminiarFichasQuincena/' , 'PagoController@elminiarFichasQuincena');

Route::get('moraSinSaldo/' , 'PagoController@moraSinSaldo');

Route::get('pagosVencidos/' , 'PagoController@pagosVencidos');
Route::get('pagosVencidos2/' , 'PagoController@pagosVencidos2');
Route::get('intentoTres/' , 'PagoController@intentoTres');
Route::get('cuentaFichas/' , 'PagoController@cuentaFichas');

Route::get('/', ['as' => 'home','uses' => 'HomeController@index'])->middleware('auth','revalidate');
Route::get('home/api', 'HomeController@apiCreditos')->name('home.apiCreditos')->middleware('auth');
Route::get('home/apiAsesor', 'HomeController@apiAsesor')->name('home.apiAsesor')->middleware('auth');
Route::get('home/detalles/{id}', 'HomeController@detallesRapidos')->name('home.detallesRapidos')->middleware('auth');
Route::get('home/detallesAsesor/{id}', 'HomeController@detallesAsesor')->name('home.detallesAsesor')->middleware('auth');
Route::get('home/apiCreditos/{id}', 'HomeController@apiAsesorCredito')->name('home.apiAsesorCreditos')->middleware('auth');
Route::get('home/apiCuadre', 'HomeController@apiCuadre')->name('home.apiCuadre')->middleware('auth');

Route::get('/tabla/creditos', 'HomeController@tablaCreditos')->name('tabla.creditos');
Route::get('/tabla/asesor', 'HomeController@tablaAsesor')->name('tabla.asesor');
Route::get('/tabla/general', 'HomeController@tablaGeneral')->name('tabla.general');

Route::get('/tabla/pago/pendientes', 'PagoController@tablaPendiente')->name('tabla.pagos2.pendientes');
Route::get('pagos/api/pendiente', 'PagoController@apiPendientes')->name('pagos.apiPendientes')->middleware('auth');
//Rutas de clientes
//***********************************************CLIENTES************************************************
Route::resource('clientes', 'ClientesController')->middleware('auth','role:Administrador.Secretaria.Supervisor');
Route::get('cumple/', ['as' => 'clientes.cumple', 'uses' => 'ClientesController@cumpleanios'])->middleware('auth','revalidate');
Route::get('infomacion/cumple', ['as' => "info.cumpleanios", 'uses' => 'ClientesController@infoCumpleanios'])->middleware('auth','revalidate');
Route::get('clientes/listaNB/{id}', ['as' => 'clientes.ln', 'uses' => "ClientesController@listaNB"])->middleware('auth','revalidate', 'role:Administrador.Secretaria.Supervisor');
Route::get('api/infoCliente/{id}', ['as' => 'info.cliente', 'uses' => "ClientesController@infoCliente"])->middleware('auth','revalidate');
Route::post('clientes/quitarCumple/{id}', ['as' => 'clientes.quitarCumple', 'uses'  => 'ClientesController@quitarCumple'])->middleware('auth','revalidate');
Route::post('add_img/cliente/{id}',['as' => "clientes.add_img", 'uses' => 'ClientesController@agregarImagen'])->middleware('auth','revalidate');
Route::get('dataClientes',['as' => 'clientes.tableCliente', 'uses' =>  'ClientesController@tableCliente'])->middleware('auth', 'revalidate');


//Rutas de transferencia
Route::put('transferencia/ruta' ,['as' => 'ruta.transferir', 'uses' => 'RutaController@transferir'])->middleware('auth', 'revalidate');
Route::put('transferencia/cliente/{id}', ['as' => 'clientes.transferir', 'uses' => 'ClientesController@transferir'])->middleware('auth','revalidate','role:Administrador.Supervisor');
Route::get('api/promotor/ruta/{id}', ['as' => 'ruta.promotor', 'uses' => 'RutaController@infoPromotor'])->middleware('auth','revalidate', 'role:Administrador.Secretaria.Supervisor');
Route::get('info/transferecia/ruta/{id}', ['as' => 'ruta.infoRuta','uses' => 'RutaController@transferenciaRuta'])->middleware('auth','revalidate', 'role:Administrador.Supervisor');

//Rutas de creditos
//************************************************CREDITOS**********************************************
Route::resource('creditos', 'CreditosController')->middleware('asueto');
// Route::get('creditos/', ['as' => 'creditos.index', 'uses' => 'CreditosController@entregados'])->middleware('auth');
// Route::get('creditos/create', ['as' => 'creditos.create', 'uses' => 'CreditosController@create'])->middleware('auth');
// Route::POST('creditos', ['as' => 'creditos.store', 'uses' => 'CreditosController@store'])->middleware('auth');
// Route::get('creditos/{creditos}', ['as' => 'creditos.show', 'uses' => 'CreditosController@show'])->middleware('auth');
// Route::get('creditos/{creditos}/edit', ['as' => 'creditos.edit', 'uses' => 'CreditosController@edit'])->middleware('auth');
// Route::put('creditos/{creditos} ' ,['as' => 'creditos.update', 'uses' => 'CreditosController@update'])->middleware('auth');

// GET           /users                      index   users.index
// GET           /users/create               create  users.create
// POST          /users                      store   users.store
// GET           /users/{user}               show    users.show
// GET           /users/{user}/edit          edit    users.edit
// PUT|PATCH     /users/{user}               update  users.update
// DELETE        /users/{user}               destroy users.destroy
Route::get('entregados/', ['as' => 'creditos.entregados', 'uses' => 'CreditosController@entregados'])->middleware('auth');
Route::get('proxFinalizar/', ['as' => 'creditos.finalizar', 'uses' => 'CreditosController@finalizar'])->middleware('auth','revalidate');
Route::get('renovacion/{id}', ['as' => 'creditos.renovacion', 'uses' => 'CreditosController@renovar'])->middleware('auth','revalidate');
Route::post('renovacion/create', ['as' => 'creditos.renoCreate', 'uses' => 'CreditosController@renovacionCreate'])->middleware('auth');
Route::get('fecha_especial' , ['as' => 'creditos.fecha', 'uses' => 'CreditosController@fecha_esp'])->middleware('auth','revalidate','role:Administrador.Supervisor');
Route::post('fecha_create' , ['as' => 'creditos.fecha_create', 'uses' => 'CreditosController@fecha_create'])->middleware('auth','revalidate', 'role:Administrador.Supervisor');
Route::get('api/infoCredito/{id}', ['as' => 'info.credito', 'uses' => 'CreditosController@credinfo'])->middleware('auth','revalidate');
Route::post('api/pago/credito/{id}', ['as' => 'pagoCreditoVencido', 'uses' => 'PagoController@pagoVencido'])->middleware('auth','revalidate');

resources/views/Creditos/cartera.blade.php
@extends('layouts.app')

@section('title', 'Cartera')

@section('content')

@section('nombre','Cartera')
@section('ruta')
  <li class="active">
      <strong>Cartera</strong>
  </li>
@endsection
    <div class="wrapper wrapper-content animated fadeInRight">
                <div class="row">
                  <div class="col-lg-4">
                      <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h5>Cartera</h5>
                            </div>
                            <div>
                                <div class="ibox-content profile-content">
                                  <h4>{{$cartera->prestamos->count()}}</h4>
                                  <strong class="text-success">Datos de cartera</strong>

                                  <ul class="list-group clear-list">
                                    <li class="list-group-item fist-item">
                                        <span class="pull-right">{{$cartera->nombre}}</span>
                                        Nombre
                                    </li>
                                      <li class="list-group-item">
                                          <span class="pull-right">{{$cartera->user}}</span>
                                          Promotor
                                      </li>
                                      <li class="list-group-item">
                                          <span class="pull-right"> {{$cartera->activa}} </span>
                                          Estado
                                      </li>
                                  </ul>
                                    <div class="user-button">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <button type="button" class="btn btn-primary btn-sm btn-block"><i class="fa fa-envelope"></i> Documentos</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                      </div>
                  </div>

                  <div class="col-md-8">
                      <div class="ibox float-e-margins">
                          <div class="ibox-title">
                              <h5>Carteras</h5>
                              <div class="ibox-tools">
                                  <a class="collapse-link">
                                      <i class="fa fa-chevron-up"></i>
                                  </a>
                                  <a class="close-link">
                                      <i class="fa fa-times"></i>
                                  </a>
                              </div>
                          </div>
                          <div class="ibox-content">
                            <div class="table-responsive">
                              <table class='table table-striped table-hover'>
                                <thead>
                                  <tr>
                                    <th>Código</th>
                                    <th>Monto</th>
                                    <th>Estado</th>
                                    <th>Cliente</th>
                                  </tr>
                                </thead>
                                <tbody>

                                    @foreach ($cartera->prestamos as $prestamo)
                                    <tr>
                                      <td>{{$prestamo->id}}</td>
                                      <td>{{$prestamo->monto}}</td>
                                      @if($prestamo->activo === 1)
                                        <td><a><span class="badge badge-primary pull-center">activo</span></a></td>
                                      @else
                                        <td><a><span class="badge badge-danger pull-center">terminado</span></a></td>
                                      @endif
                                      <td>{{$hoja_ruta->nombre}}</td>
                                      <td> {{count($hoja_ruta->ruta)}}
                                      <td class="project-actions">
                                          <a href="#" class="btn btn-success btn-sm"><i class="fa fa-folder"></i> Ver </a>
                                      </td>
                                    </tr>
                                    @endforeach
                                </tbody>

                              </table>
                            </div>

                          </div>

                          </div>
                      </div>

                  </div>

            </div>
@endsection

resources/views/Creditos/entregados.blade.php
@extends('layouts.app')

@section('title', 'Creditos')

@section('content')

@section('nombre','Creditos')
@section('ruta')
  <li class="active">
      <strong>Creditos a entregar</strong>
  </li>
@endsection
    <div class="wrapper wrapper-content animated fadeInRight">
                <div class="row">
                    <div class="col-sm-12">
                      <div class="ibox float-e-margins">
                        <div class="ibox-title">
                          <h5>Prestamos a entregar</h5>
                        </div>
                        <div class="ibox-content">
                          <div class="input-group">
                              <input type="text" placeholder="Buscar credito " class="input form-control">
                              <span class="input-group-btn">
                                      <button type="button" class="btn btn btn-primary"> <i class="fa fa-search"></i> Buscar</button>
                              </span>
                          </div>
                          <ul class="nav">
                            <p><span class="pull-left text-muted">Pagos</span></p>
                          </ul>
                          <div class="table-responsive">
                            <table class='table table-striped table-hover'>
                              <thead>
                                <tr>
                                  <th>Prestamo</th>
                                  <th>Monto</th>
                                  <th>Cliente</th>
                                  <th>Cod. Cliente</th>
                                  <th>Accion</th>
                                </tr>
                              </thead>
                              <tbody>
                                 @foreach ($prestamos as $prestamo)
                                  <tr>
                                    <td><a href="{{route('creditos.show', $prestamo->id)}}" class="client-link">Cre-{{$prestamo->id}}</a></td>
                                    <td>{{$prestamo->monto}}</td>
                                    <td>{{$prestamo->cliente->persona->nombre}} {{$prestamo->cliente->persona->apellido}}</td>
                                    <td><a href="{{route('clientes.show',$prestamo->cliente->id)}}" class="client-link">Cli-{{$prestamo->cliente->id}}</a></td>
                                    <td><a id="#btnbus" href="#" value="{{$prestamo->cliente->id}}" class="btn btn-outline  btn-info entregar"><i class="fa fa-truck entregar-hijo" value="{{$prestamo->id}}"></i></a></td>
                                  </tr>
                                @endforeach
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>


                    </div>
                </div>
            </div>
@endsection

@section('scripts')

<script type="text/javascript">
  var idCliente;
  var idPrestamo;
  $(document).ready(function(){
    $(".entregar").click(function(){
      idCliente = $(this).attr("value");
      idPrestamo = $(this).children('.entregar-hijo').attr("value");
      console.log(idPrestamo);
      if (navigator.geolocation)
        {
        /* la geolocalizacion esta disponible */
          navigator.geolocation.getCurrentPosition(gpsActivado, errorMetodo, {enableHightAccuracy: true, timeout:Infinity, maximage:0});
        }
      else
        {
          console.log('Ocurrio un error, intentelo otra vez');
        }
})

    function gpsActivado(position){
      var latitud = position.coords.latitude;
      var longitud = position.coords.longitude;
      var precision = position.coords.accuracy;
      var tiempo = position.timestamp;
      console.log(latitud, longitud, precision, tiempo, idPrestamo);
      sendLocation(latitud, longitud, idCliente);
    }

    function errorMetodo(){
      alert('GPS no activado');
    }

    function sendLocation(lat, lon, id){
      // var id = $(this).attr("value");
      url = '{{url('coordenadas/cliente/')}}';
      $.ajax({
          type: "GET",
          url: url,
          data: {
            'latitude' : lat,
            'longitude': lon,
            'secret'  : id,
            'prestamoid' : idPrestamo
          },success: function(html){
            location.reload();
          }
      });
      console.log('ENTRO');
    }
  });
</script>

@endsection

resources/views/Creditos/fecha_descanso.blade.php
@extends('layouts.app')

@section('title', 'Fechas especiales')

@section('content')

  @section('nombre','Creditos')
  @section('ruta')
    <li class="active">
        <strong>Fechas especiales</strong>
    </li>
  @endsection
  <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
              <div class="ibox">
                <div class="ibox-title">
                  <h5>Fecha especiales</h5>
                </div>
                <div class="ibox-content">
                  <h5 class="text-success">Agregar fecha:</h5>
                  <hr>
                  <div class="row">
                    {!! Form::  open(['id'=> 'form-credito', 'route'  => 'creditos.fecha_create','method' => 'POST']) !!}
                    <div class="form-group col-sm-4">
                      {{ Form::label('name', 'Fecha') }}
                      {{ Form::Date('fecha', \Carbon\Carbon::now(), ['class' => 'form-control', 'id' => 'nombre' ]) }}
                    </div>
                    <div class="form-group col-sm-8">
                      {{ Form::label('name', 'Descripcion') }}
                      {{ Form::text('descripcion', null, ['class' => 'form-control', 'id' => 'nombre' ]) }}
                    </div>
                    {!! Form::submit('Crear', ['class' => 'btn btn-info']) !!}
                    {{Form::close()}}
                    <div class="col-md-12">
                      <h5 class="text-info">Fechas actuales:</h5>
                      <div class="table-responsive">
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th>No.</th>
                            <th>Fecha</th>
                            <th>Descripcion</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($fechas as $fecha)
                            <tr>
                              <td>{{$fecha->id}}</td>
                              <td>{{$fecha->fecha}}</td>
                              <td>{{$fecha->descripcion}}</td>
                            </tr>
                          @endforeach

                        </tbody>
                      </table>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Creditos/modalTemp.blade.php
<div class="row">
  <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="row">
          <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Pago</h5>
        </div>
        <div class="ibox-content">
          {!! Form::  open(['id'=> 'formulario','route' => 'pagos.store', 'method' => 'POST']) !!}
          <div class="form-row col-sm-12">
              <div class="form-group col-sm-6">
                {{ Form::label('name', 'Cliente') }}
                {{ Form::text('nom_cliente', null, ['class' => 'form-control', 'id' => 'nom_cliente']) }}
                {{ Form::hidden('cliente', null, array('id' => 'cliente')) }}
              </div>
              <div class="form-group col-sm-6">
                {{ Form::label('name', 'No. cuota') }}
                {{ Form::text('no_cuota', null, ['class' => 'form-control', 'id' => 'no_cuota']) }}
              </div>
          </div>

          <div class="form-row col-sm-12">
            <div class="form-group col-sm-4">
              {{ Form::label('name', 'Cuota') }}
              {{ Form::text('cuota', null, ['class' => 'form-control', 'id' => 'cuota']) }}
            </div>
            <div class="form-group col-sm-8">
                {{ Form::label('name', 'Observaciones') }}
                {{ Form::text('observaciones', null, ['class' => 'form-control', 'id' => 'nit' ]) }}
            </div>
          </div>

          <div class="form-row">
              <div class="form-group" id="guardar">
                {{ Form::submit('Pago', ['class' => 'btn btn-md btn-primary', 'name' => 'submitbutton', 'value' => 'pago']) }}
                {{ Form::submit('No pago',['class' => 'btn btn-md btn-danger','name' => 'submitbutton', 'value' => 'no_pago'])}}
                {{-- {{ Form::button('Pendiente',['class' => 'btn btn-md btn-warning','name' => 'submitbutton', 'value' => 'no_pago'])}} --}}
            </div>
          </div>
        </div>
      {!! Form::close() !!}
      </div>
    </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/Creditos/modelRevertir.blade.php
<div class="row">
  <div id="modal-revertir" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="row">
          <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Cambiar estado pago</h5>
        </div>
        <div class="ibox-content">
          {!! Form::  open(['id'=> 'formulario','route' => 'pagos.store', 'method' => 'POST']) !!}
          <div class="form-row col-sm-12">
              <div class="form-group col-sm-6">
                {{ Form::label('name', 'Cuota') }}
                {{ Form::text('cuota', null, ['class' => 'form-control', 'id' => 'rev_cuota']) }}
              </div>
              <div class="form-group col-sm-6">
                {{ Form::label('name', 'No. cuota') }}
                {{ Form::text('no_cuota', null, ['class' => 'form-control', 'id' => 'no_cuota']) }}
              </div>
          </div>

          <div class="form-row">
              <div class="form-group" id="guardar">
                {{-- {{ Form::submit('Pago', ['class' => 'btn btn-md btn-primary', 'name' => 'submitbutton', 'value' => 'pago']) }} --}}
                {{-- {{ Form::submit('No pago',['class' => 'btn btn-md btn-danger','name' => 'submitbutton', 'value' => 'no_pago'])}} --}}
                {{-- {{ Form::button('Pendiente',['class' => 'btn btn-md btn-warning','name' => 'submitbutton', 'value' => 'no_pago'])}} --}}
            </div>
          </div>
        </div>
      {!! Form::close() !!}
      </div>
    </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/Creditos/proxFinalizar.blade.php
@extends('layouts.app')

@section('title', 'Creditos')

@section('content')

@section('nombre','Creditos')
@section('ruta')
  <li class="active">
      <strong>Creditos a finalizar</strong>
  </li>
@endsection

@section("link")
<link href="{{asset('css/rangedatepicker/daterangepicker.css')}}" rel="stylesheet"  media="screen">
@endsection

@php
  use Carbon\Carbon;
  setlocale(LC_TIME, 'es_AR.utf8');
  Carbon::setUtf8(false);
@endphp
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
      <div class="col-sm-12">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Prestamos a finalizar</h5>
          </div>
          <div class="ibox-content">
            <div class="row">
              <ul class="nav">
                <p><span class="pull-left text-muted">{{$prestamos->count()}} Prestamos</span></p>
              </ul>
              <label class="col-md-12">Rango:</label>
              <div class="col-md-12">
                <div class="col-sm-6">
                  <div class="input-group">
                    <div class="form-group">
                      <input id="rangedate" class="form-control" type="text" name="" value="">
                    </div>
                    <span class="input-group-btn">
                      <a id="busqueda_fecha" class="btn btn-primary"> <i class="fa fa-search"></i> Buscar</a>
                    </span>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="table-responsive">
                <table id="tabla_fin" class='table table-striped table-hover'>
                  <thead>
                    <tr>
                      <th>Prestamo</th>
                      <th>Monto</th>
                      <th>Clasificacion</th>
                      <th>Fecha final</th>
                      <th>Cliente</th>
                      <th>Promotor</th>
                    </tr>
                  </thead>
                  <tbody>
                     @foreach ($prestamos as $prestamo)
                      <tr>
                        <td>Cre-{{$prestamo->id}}</td>
                        <td>{{$prestamo->monto}}</td>
                        {!!$prestamo->obtenerClasificacion()!!}
                        <td>{{Carbon::parse($prestamo->fecha_fin)->formatLocalized('%A') ." " . Carbon::parse($prestamo->fecha_fin)->format('d-m-y')}}</td>
                        <td>{{$prestamo->cliente->persona->nombre}} {{$prestamo->cliente->persona->apellido}}</td>
                        <td>{{$prestamo->ruta->first()->hoja_ruta->user->persona->nombre}} {{$prestamo->ruta->first()->hoja_ruta->user->persona->apellido}}</td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
@endsection

@section('scripts')
<script type="text/javascript" src="{{asset('js/moment/moment.js')}}"></script>
<script type="text/javascript" src="{{asset('js/rangedatepicker/daterangepicker.js')}}"></script>

<script type="text/javascript">
var datos;
$("#rangedate").daterangepicker({
  "locale": {
    "format": "DD/MM/YYYY",
    "fromLabel": "Desde",
    "toLabel": "Hasta",
    "applyLabel": "Aplicar",
    "cancelLabel": "Cancelar",
    "daysOfWeek": [
      "Dom",
      "Lun",
      "Mar",
      "Mie",
      "Jue",
      "Vie",
      "Sab"
    ],
    "monthNames": [
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre"
    ],
  }
});

$(document).ready(function(){
  $("#busqueda_fecha").click(function(){
    var tabla = $("#tabla_fin tbody")
    var rango_fechas = $("#rangedate").val();
    var valores = rango_fechas.split(' - ');
    var inicio = valores[0];
    var fin = valores[1];
    var url = "{{route('creditos.apifinalizar')}}";
    $.ajax({
        type: "GET",
        url: url,
        data: {
          'inicio' : inicio,
          'fin'    : fin,
      },
        success: function( response ) {
          tabla.html("");
          datos = response;
          var url_cliente = "{{route('clientes.show',":id")}}"
          for (var i = 0; i < datos.length; i++) {
            var datos_ac = datos[i][0];
            var url2 = url_cliente;
            url2 = url2.replace(':id', datos_ac.id_cliente);
            var new_tr =
            "<tr>" +
              "<td>Cre-" + datos_ac.id + "</td>" +
              "<td>" + datos_ac.monto + "</td>" +
                       datos_ac.clasificacion +
              "<td>" + datos_ac.fecha_final + "</td>" +
              "<td><a class='client-link' href="+ url2 +">" + datos_ac.cliente + "</a></td>" +
              "<td>" + datos_ac.promotor + "</td>" +
            "</tr>"
            tabla.append(new_tr);
          }
        }
    });
  });
});
</script>
@endsection